testfactors["Free Chlorine"] = {factorcode=2, decimals=2};
testfactors["Total Chlorine"] = {factorcode=3, decimals=2};
testfactors["Bromine"] = {factorcode=5, decimals=2};
testfactors["Biguanide"] = {factorcode=6, decimals=0};
testfactors["Shock"] = {factorcode=7, decimals=0};
testfactors["pH Low"] = {factorcode=8, decimals=2};
testfactors["pH Mid"] = {factorcode=8, decimals=2};
testfactors["pH High"] = {factorcode=8, decimals=2};
testfactors["pH"] = {factorcode=8, decimals=2};
testfactors["pH (Salt)"] = {factorcode=8, decimals=2};
testfactors["ALK"] = {factorcode=9, decimals=0};
testfactors["Hardness"] = {factorcode=10, decimals=0};
testfactors["Hardness HR"] = {factorcode=10, decimals=0};
testfactors["Hardness LR"] = {factorcode=10, decimals=0};
testfactors["Calcium Only"] = {factorcode=11, decimals=0};
testfactors["CYA"] = {factorcode=12, decimals=0};
testfactors["Copper"] = {factorcode=16, decimals=2};
testfactors["Iron"] = {factorcode=13, decimals=2};
testfactors["Total Iron"] = {factorcode=13, decimals=2};
testfactors["Ferrus Iron"] = {factorcode=15, decimals=2};
testfactors["Phosphate"] = {factorcode=18, decimals=0};
testfactors["Borate"] = {factorcode=17, decimals=0};
testfactors["Salt"] = {factorcode=19, decimals=0};
testfactors["Ammonia"] = {factorcode=54, decimals=2};
testfactors["Nitrite"] = {factorcode=21, decimals=2};
testfactors["Nitrate"] = {factorcode=20, decimals=0};
testfactors["Calcium"] = {factorcode=11, decimals=0};
testfactors["Magnesium"] = {factorcode=67, decimals=0};
testfactors["Mg 1"] = {factorcode=67, decimals=0};
testfactors["Mg 2"] = {factorcode=67, decimals=0};
testfactors["Mg 3"] = {factorcode=67, decimals=0};
testfactors["Mg 4"] = {factorcode=67, decimals=0};
testfactors["Phosphate ppm"] = {factorcode=18, decimals=2};
testfactors["Phosphate HR"] = {factorcode=18, decimals=0};
testfactors["Silica"] = {factorcode=57, decimals=0};
